### ISSUE TITLE
doesn't work with exodus

### ISSUE THREAD

**Issue by djay** [cibboy/script.profilecleaner#3]
or rather it assumes the thumbnails you need are ones associated with your media library. if you mainly use plugins for streaming and don't download it will end up removing almost all the thumbnails. 

Not sure how to fix this but I had one idea. I'm assuming you can't easily get access to the texture database like "texture cache maintenance utility" and therefore you can't find out when thumbnails were last used. In which case you could periodically remove thumbnails based on their file modification date, e.g. 20% of the oldest and record it in a database. If they get redownloaded on the next purge you add them to an exluded list. This way can build up your own database of how often thumbnails are used and which are better purge.

**Comment by cibboy** [comment]
I'll close the issue as Exodus is no longer in support.
PR #4 by @Palindrones updates this addon to support Kodi 19 (Matrix).
